name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    strategy:
      matrix:
        os-type: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        node-version: [14.x, 16.x, 18.x] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ${{ matrix.os-type }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version:
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
